### ISSUE TITLE
Should have X Cores, but only found X for Die

### ISSUE THREAD

**Issue by reteps** [Shaneee92/Mojave_AMD_XNU#1]
Listed here to keep track of the progress of this issue. ~Currently experienced by multiple discord users~

https://github.com/Shaneee92/Mojave_AMD_XNU/blob/4e0ec7372aaa6f457baad7027c48f91f110b08fc/osfmk/i386/cpu_threads.c#L1070

https://github.com/Shaneee92/Mojave_AMD_XNU/blob/4e0ec7372aaa6f457baad7027c48f91f110b08fc/osfmk/kern/waitq.c#L2719

**Comment by reteps** [comment]
Fixed with this prelinkedkernel: https://cdn.discordapp.com/attachments/458386099815972864/527600395498029056/prelinkedkernel.test.zip

**Comment by Shaneee** [comment]
Fix here, https://github.com/Shaneee92/Mojave_AMD_XNU/commit/e2e00576f19e2078b04e2cc2ca52a209f6aa46c4
